### PR TITLE
feat: Adding superclustering

### PR DESCRIPTION
**Pull request by etiennedreyer**
This PR introduces a reconstruction utility for primary electrons and those coming from photon conversions, which can be enabled by adding `Do_superclustering: true` in the config. The new functionality comes mainly by three new files:
- [src/Supercluster.cc](https://github.com/scd-hep/scd-hep/pull/15/files#diff-0d3cb20cc49f40d5e7ff9fe6dc7384cc3bff141d633b08b3c3389158204e22ee)
- [src/Superclustering.cc](https://github.com/scd-hep/scd-hep/pull/15/files#diff-e7e441c54231442ea0a38eb5a411dfcfc130a961e42abe636d7032e747e476be)
- [src/Superclustering_data.cc](https://github.com/scd-hep/scd-hep/pull/15/files#diff-e857ff907e5e208c17f6b0e614342da3b184d85e410e25d06ca599534d515cdb)

`src/Superclustering.cc` takes as input the lists of cells, tracks, and topoclusters and performs matching and supercluster formation in 6 steps:

https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/src/Superclustering.cc#L45-L57

The original lists are unchanged by this operation, which follows after running pflow and before graph creation in `src/EventAction.cc`:
https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/src/EventAction.cc#L214

Two new classes are introduced for the task of superclustering:
- https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/include/Supercluster.hh#L11
- https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/include/Supercluster.hh#L35

The results are stored in a vector of `Supercluster` objects called `superclustering_data.super_list`. This is written to branches in the output tree in `src/Superclustering_data.cc`.

The places where the incoming feature could affect the existing behavior is in the handling of conversion tracks. This PR introduces a looser requirement of track origin R in case the track is from a photon conversion:
https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/src/Track_var.cc#L65-L71
However, conversion tracks are still handled separately in `trajectories.fAllConvElectrons` from the rest of tracks (`trajectories.fAllTrajectoryInfo`). Only when `Do_superclustering` is enabled are these two lists concatenated so that track parameters can be computed for both in one go:
https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/src/EventAction.cc#L192-L198

### CODE REVIEW

**Comment by etiennedreyer** [comment]
HI @pariRieck @sanmayphy this is ready to be reviewed

**Comment by pariRieck** [comment]
Hi @etiennedreyer , this is a huge PR. Please add a description here about what it does. We should all do that for larger review requests.

**Comment by etiennedreyer** [comment]
Hi @pariRieck I added an overview of the code changes in the description of the PR. Please have a look...

**Comment by pariRieck** [comment]
Hi @etiennedreyer , thank you very much for your detailed explanations here. I'm still reviewing the PR. Two things for now:

- We can ignore the failed detector response test. With a change from another PR merged meanwhile, it should pass. Anyway, the results looks Ok for the hadron response test.
- Why do you choose such a complicated definition of "is_inside_R" ( Track_var.cc ). For the definition of conversion tracks we chose something much simple and that was accepted: https://github.com/scd-hep/scd-hep/blob/main/SCD/src/TrackingAction.cc#L204

**Comment by pariRieck** [comment]
About standard tracks versus conversion tracks: the conversion tracks were introduced separately such that the standard tracks are not touched. Note that we have no tests in place for these tracks at this point.

If you now merge the two lists, I am not sure if that preserves the logic of the code everywhere. Also it is confusing to have conversion tracks in or out of the standard track list depending on the super cluster option being on or off.

**Comment by pariRieck** [comment]
A technical note: does this function actually change the lists that it receives?

https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/src/Superclustering.cc#L45

If not, it should take them as const.

**Comment by etiennedreyer** [comment]
> A technical note: does this function actually change the track, cell and topo cluster lists that it receives (1st 3 arguments)?
> 
> https://github.com/scd-hep/scd-hep/blob/c76aa90ea8f8ac0bd6349f34c8a530fbd523d513/SCD/src/Superclustering.cc#L45
> 
> If not, it should take them as const.

These input vectors are not changed, correct. So I have made them const type

**Comment by etiennedreyer** [comment]
Okay, thanks for the merge @sanmayphy . Just for closure, I did check that when I do the following two jobs (with the same seed=10), the output files contain exactly the same entries:
- on b_superclustering (Do_superclustering=false in the config)
- on main
I checked the following branches:
- track_qoverp
- track_phi_layer_2
- track_not_reg
- conv_el_px

I checked this for both a W leptonic sample and photon gun sample (with conversions). On the other hand, when Do_superclustering is turned on, the conversion tracks are indeed stored in the main track list. This pooling of the primary and conversion track lists can be changed in the future, but at least for now this check confirms that it doesn't affect the output when Do_superclustering is turned off by user (default).

**Pull request merged**
